### ISSUE TITLE
Would it be possible to generate a new version of these files?

### ISSUE THREAD

**Issue by Multiply** [contentstack/contentstack-openapi#2]
The current files are riddled with tiny mistakes, and we have to manually patch them up for them to be useful to us.

Would it be possible for you to generate a fresh version that more correctly reflects the API?

**Comment by sunilnadar** [comment]
Hi,
We have generated new files with the updated features, as well as fixed a lot of issues.
We also have the postman collections for the same - https://github.com/contentstack/contentstack-postman-collections
